### ISSUE TITLE
Would you be open to making a recommended path more clear in this guide?

### ISSUE THREAD

**Issue by bitemyapp** [katychuang/getting-started-with-haskell#3]
Some of the links are to material intended for beginners to learn Haskell with from scratch, some are to general references, tips, etc. Is this repo for beginners looking for clear guidance on where to begin or is it something other than that? (I may very well have misunderstood)

**Comment by katychuang** [comment]
Excellent questions! Honestly, I don't know what the best path is for learning Haskell from scratch, so as a work in progress guide I'm open to suggestions for improvement. One aspect in particular that I wanted to focus on for this guide is the aspect of writing code and running it in ghc(i) more than the theories, so the tutorials are akin to cookbooks. There very well could be better vocabularies and better separation of content to make everything clearer. Do you have any immediate suggestions for making the guide clearer?

**Comment by bitemyapp** [comment]
I don't want to reshape it in my own image. There's a different angle that could be taken here.

I've explained a lot of why I do or do not recommend particular resources [here](http://bitemyapp.com/posts/2014-12-31-functional-education.html).

I don't know your intent with this repo. I could answer questions, provide background on what's worked in getting new people up to speed so you could come to your own conclusions. If you don't have time, can leave it for another day.

**Comment by katychuang** [comment]
Thanks for the link, I'll take a look. I'm at a conference today and the rest of the week, so discussing at another time would be better when I can give full attention.
